plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'org.jetbrains.kotlin.kapt'
    id 'dagger.hilt.android.plugin'
    id 'kotlin-kapt'
    id 'androidx.navigation.safeargs'
    id 'kotlin-parcelize'
    id 'com.google.devtools.ksp'
}

android {
    namespace 'ru.abenda.marsexplorer'

    compileSdkVersion 35
    buildToolsVersion "35.0.0"

    defaultConfig {
        applicationId "ru.abenda.marsexplorer"
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 2
        versionName "1.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        buildConfigField("String", "API_KEY", "\"hAOq3n74BaKmh8m7BDB6qvfeuIUx6Rk9zsRdzVDE\"")
        buildConfigField("String", "BASE_URL", "\"https://api.nasa.gov/mars-photos/api/v1/\"")

        multiDexEnabled = true

        javaCompileOptions {
            annotationProcessorOptions {
                arguments += [
                        "room.schemaLocation":"$projectDir/schemas".toString(),
                        "room.incremental":"true",
                        "room.expandProjection":"true"]
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        dataBinding true
        buildConfig true
    }
}

dependencies {

    implementation(libs.kotlin.stdlib)
    implementation libs.core.ktx
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraint.layout
    implementation libs.legacy.support.v4
    implementation libs.lifecycle.livedata.ktx
    implementation libs.work.runtime.ktx
    testImplementation libs.junit
    androidTestImplementation libs.junit.ext
    androidTestImplementation libs.espresso

    // Hilt
    implementation libs.hilt.dagger.android
    ksp libs.dagger.hilt.compiler
    implementation libs.hilt.work
    ksp libs.hilt.compiler

    // For instrumentation tests
    androidTestImplementation  libs.dagger.hilt.android.testing
    kspAndroidTest libs.dagger.hilt.compiler
    // For local unit tests
    testImplementation libs.dagger.hilt.android.testing
    kspTest libs.dagger.hilt.compiler

    // Multidex
    implementation libs.multidex

    // ViewModel and LiveData
    implementation(libs.lifecycle.viewmodel.ktx)

    // Navigation
    implementation(libs.navigation.fragment.ktx)
    implementation(libs.navigation.ui.ktx)

    // Moshi
    implementation(libs.moshi)
    implementation(libs.moshi.kotlin)
    implementation(libs.moshi.adapters)


    // Retrofit
    implementation(libs.retrofit) {
        exclude group: 'com.squareup.okhttp3', module: 'okhttp'
    }

    // OkHttp
    implementation(libs.okhttp)
    implementation(libs.okhttp.logging.interceptor)

    // Retrofit with Moshi Converter
    implementation(libs.retrofit.converter.moshi)

    // Glide
    implementation(libs.glide)

    // RecyclerView
    implementation(libs.recyclerview)

    // Paging
    implementation(libs.paging.runtime.ktx)

    // Room
    implementation(libs.room.runtime)
    implementation(libs.room.ktx)
    implementation(libs.room.paging)
    ksp(libs.room.compiler)
    testImplementation(libs.room.testing)

    // Timber logging
    implementation(libs.timber.logging)
}
